networkRules: &networkRules
  allowIPs: false
  allowPrivate: false
  allowHTTP: true
  blockedDomains:
    - "*.cluster.local"
    - "scc-controlplane-service"
    - "scc-builder-service"

capabilities:
  http:
    enabled: true
    rules: *networkRules
  graphql:
    enabled: true
    rules: *networkRules
  logger:
    enabled: true
  cache:
    enabled: false
