[package]
name = "helloworld"
version = "0.8.0"
authors = ["Connor Hicks <connorjhicks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
suborbital = '0.4.2'